### ISSUE TITLE
Move article extractor into storyweb

### ISSUE THREAD

**Issue by pudo** [opensanctions/storyweb#12]
This is in mediacrawl right now, but could be in the app itself so users can submit URLs to be loaded as articles.

**Comment by slavaGanzin** [comment]
Hello, Friedrich. 

Interesting project. Following your progress with interest. I think journalism could benefit from the more connected knowledge graph inlined in articles because it's really hard to keep all these links and facts inside your head. 

I work for https://newscatcherapi.com/, we have decent plans for startups and NGOs. So, if you want to try offloading the article collection, so you could concentrate on other parts of stroryweb, just ping me.

**Comment by pudo** [comment]
Hey @slavaGanzin, thanks a ton for reaching out. I just went through the newscatcher site and documentation a bit, and really quite like what you're doing. It looks nicely engineered and not overstated in its scope. I also like a lot that you're providing free access to NGOs.

I wonder if we should have a call to discuss a possible collaboration? What you're doing is super complementary with OpenSanctions... https://calendly.com/flindenberg/opensanctions-intro?month=2022-12

**Comment by slavaGanzin** [comment]
@pudo Let's have a call with me and our CEO. Booked a meeting on Tuesday at 12:00. Check an invite, please

**Comment by pudo** [comment]
Next up: figure out how to auto-merge entities from a new article on a story level.
